[opener]
extract = [
	{ run = 'unzip -qo %s', desc = "Extract here", for = "unix" },
	{ run = 'ya pub extract --list %s', desc = "Extract here", for = "windows" },
]
play = [
	{ run = 'xdg-open %s1', orphan = true, desc = "Play" },
]
open = [
	{ run = 'xdg-open %s1', orphan = true, desc = "Open" },
]
