opener: nvim
wrappers:
  kitty:
    command: kitty --title "$WF_TITLE" --directory "$WF_WORKTREE" $SHELL -c "$WF_COMMAND"
    background: true
  sh:
    command: $SHELL -c "$WF_COMMAND"
    background: false
openers:
  nvim:
    command: 'nvim "$WF_TARGET"'
    wrap: kitty
  claude:
    command: claude
    wrap: kitty
  zsh:
    command: zsh
    wrap: kitty
  lazygit:
    command: lazygit
    wrap: kitty
  code:
    command: 'code "$WF_TARGET"'
    background: true
